version: '3.9'

services:
  main-app:
    container_name: main-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: uvicorn --factory app.main:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ..:/code/
    ports:
      - ${APP_HOST}:${APP_PORT}:8000
    env_file:
      - ../.env
#    depends_on:
#      - mongodb
    networks:
      - backend


networks:
  backend:
    driver: bridge