version: '3.9'

services:
  mongodb:
    container_name: mongodb-storage
    image: mongo:6-jammy
    ports:
      - ${DB_HOST}:${DB_PORT}:27017
    env_file:
      - ../.env
    volumes:
      - dbdata6:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_HOST}:${MONGO_EXPRESS_PORT}:8081
    env_file:
      - ../.env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  dbdata6:

networks:
  backend:
    driver: bridge